#############################################################################
# Makefile for building: testingSystem
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  testingSystem.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile testingSystem.pro -qtconf /usr/lib/x86_64-linux-gnu/qt5/qt.conf -early QMAKE_CC=x86_64-linux-gnu-gcc QMAKE_CXX=x86_64-linux-gnu-g++ QMAKE_LINK=x86_64-linux-gnu-g++ QMAKE_STRIP=x86_64-linux-gnu-strip QMAKE_QMAKE=/usr/bin/x86_64-linux-gnu-qmake PKG_CONFIG=x86_64-linux-gnu-pkg-config -before -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = x86_64-linux-gnu-gcc
CXX           = x86_64-linux-gnu-g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = testingSystem1.0.0
DISTDIR = /home/dan/test/CDC/.tmp/testingSystem1.0.0
LINK          = x86_64-linux-gnu-g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lcrypto -lssl -lconfig++ /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = x86_64-linux-gnu-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = core/Secure.cpp \
		core/Admin.cpp \
		core/Config.cpp \
		core/Service.cpp \
		core/admin_manager.cpp \
		core/file_manager.cpp \
		core/secure_manager.cpp \
		core/task_manager.cpp \
		core/test_case.cpp \
		core/test_manager.cpp \
		core/test_omnimanager.cpp \
		gui/adding_form.cpp \
		gui/admining.cpp \
		gui/admining_details.cpp \
		gui/auto_testing.cpp \
		gui/auto_testing_details.cpp \
		gui/change_password.cpp \
		gui/choice_tests.cpp \
		gui/edit_pass.cpp \
		gui/edit_test_case.cpp \
		gui/edit_tests_run_and_list.cpp \
		gui/hand_testing_details.cpp \
		gui/handtestingform.cpp \
		gui/login.cpp \
		gui/registration.cpp \
		gui/report.cpp \
		gui/send_form.cpp \
		gui/test_cases.cpp \
		main.cpp \
		mainwindow.cpp moc_adding_form.cpp \
		moc_admining.cpp \
		moc_admining_details.cpp \
		moc_auto_testing.cpp \
		moc_auto_testing_details.cpp \
		moc_change_password.cpp \
		moc_choice_tests.cpp \
		moc_edit_pass.cpp \
		moc_edit_test_case.cpp \
		moc_edit_tests_run_and_list.cpp \
		moc_hand_testing_details.cpp \
		moc_handtestingform.cpp \
		moc_login.cpp \
		moc_registration.cpp \
		moc_report.cpp \
		moc_send_form.cpp \
		moc_test_cases.cpp \
		moc_mainwindow.cpp
OBJECTS       = Secure.o \
		Admin.o \
		Config.o \
		Service.o \
		admin_manager.o \
		file_manager.o \
		secure_manager.o \
		task_manager.o \
		test_case.o \
		test_manager.o \
		test_omnimanager.o \
		adding_form.o \
		admining.o \
		admining_details.o \
		auto_testing.o \
		auto_testing_details.o \
		change_password.o \
		choice_tests.o \
		edit_pass.o \
		edit_test_case.o \
		edit_tests_run_and_list.o \
		hand_testing_details.o \
		handtestingform.o \
		login.o \
		registration.o \
		report.o \
		send_form.o \
		test_cases.o \
		main.o \
		mainwindow.o \
		moc_adding_form.o \
		moc_admining.o \
		moc_admining_details.o \
		moc_auto_testing.o \
		moc_auto_testing_details.o \
		moc_change_password.o \
		moc_choice_tests.o \
		moc_edit_pass.o \
		moc_edit_test_case.o \
		moc_edit_tests_run_and_list.o \
		moc_hand_testing_details.o \
		moc_handtestingform.o \
		moc_login.o \
		moc_registration.o \
		moc_report.o \
		moc_send_form.o \
		moc_test_cases.o \
		moc_mainwindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		testingSystem.pro core/Secure.hpp \
		core/Base.hpp \
		core/Admin.hpp \
		core/Config.hpp \
		core/Options.h \
		core/admin_manager.h \
		core/file_manager.h \
		core/secure_manager.h \
		core/task_manager.h \
		core/test_case.h \
		core/test_manager.h \
		core/test_omnimanager.h \
		gui/adding_form.h \
		gui/admining.h \
		gui/admining_details.h \
		gui/auto_testing.h \
		gui/auto_testing_details.h \
		gui/change_password.h \
		gui/choice_tests.h \
		gui/edit_pass.h \
		gui/edit_test_case.h \
		gui/edit_tests_run_and_list.h \
		gui/hand_testing_details.h \
		gui/handtestingform.h \
		gui/login.h \
		gui/registration.h \
		gui/report.h \
		gui/send_form.h \
		gui/test_cases.h \
		mainwindow.h core/Secure.cpp \
		core/Admin.cpp \
		core/Config.cpp \
		core/Service.cpp \
		core/admin_manager.cpp \
		core/file_manager.cpp \
		core/secure_manager.cpp \
		core/task_manager.cpp \
		core/test_case.cpp \
		core/test_manager.cpp \
		core/test_omnimanager.cpp \
		gui/adding_form.cpp \
		gui/admining.cpp \
		gui/admining_details.cpp \
		gui/auto_testing.cpp \
		gui/auto_testing_details.cpp \
		gui/change_password.cpp \
		gui/choice_tests.cpp \
		gui/edit_pass.cpp \
		gui/edit_test_case.cpp \
		gui/edit_tests_run_and_list.cpp \
		gui/hand_testing_details.cpp \
		gui/handtestingform.cpp \
		gui/login.cpp \
		gui/registration.cpp \
		gui/report.cpp \
		gui/send_form.cpp \
		gui/test_cases.cpp \
		main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = testingSystem
DESTDIR       = 
TARGET        = testingSystem


first: all
####### Build rules

testingSystem: ui_adding_form.h ui_admining.h ui_admining_details.h ui_auto_testing.h ui_auto_testing_details.h ui_change_password.h ui_choice_tests.h ui_edit_pass.h ui_edit_test_case.h ui_edit_tests_run_and_list.h ui_hand_testing_details.h ui_handtestingform.h ui_login.h ui_registration.h ui_report.h ui_send_form.h ui_test_cases.h ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: testingSystem.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		testingSystem.pro
	$(QMAKE) -o Makefile testingSystem.pro -qtconf /usr/lib/x86_64-linux-gnu/qt5/qt.conf -early QMAKE_CC=x86_64-linux-gnu-gcc QMAKE_CXX=x86_64-linux-gnu-g++ QMAKE_LINK=x86_64-linux-gnu-g++ QMAKE_STRIP=x86_64-linux-gnu-strip QMAKE_QMAKE=/usr/bin/x86_64-linux-gnu-qmake PKG_CONFIG=x86_64-linux-gnu-pkg-config -before -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
testingSystem.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile testingSystem.pro -qtconf /usr/lib/x86_64-linux-gnu/qt5/qt.conf -early QMAKE_CC=x86_64-linux-gnu-gcc QMAKE_CXX=x86_64-linux-gnu-g++ QMAKE_LINK=x86_64-linux-gnu-g++ QMAKE_STRIP=x86_64-linux-gnu-strip QMAKE_QMAKE=/usr/bin/x86_64-linux-gnu-qmake PKG_CONFIG=x86_64-linux-gnu-pkg-config -before -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile testingSystem

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents core/Secure.hpp core/Base.hpp core/Admin.hpp core/Config.hpp core/Options.h core/admin_manager.h core/file_manager.h core/secure_manager.h core/task_manager.h core/test_case.h core/test_manager.h core/test_omnimanager.h gui/adding_form.h gui/admining.h gui/admining_details.h gui/auto_testing.h gui/auto_testing_details.h gui/change_password.h gui/choice_tests.h gui/edit_pass.h gui/edit_test_case.h gui/edit_tests_run_and_list.h gui/hand_testing_details.h gui/handtestingform.h gui/login.h gui/registration.h gui/report.h gui/send_form.h gui/test_cases.h mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents core/Secure.cpp core/Admin.cpp core/Config.cpp core/Service.cpp core/admin_manager.cpp core/file_manager.cpp core/secure_manager.cpp core/task_manager.cpp core/test_case.cpp core/test_manager.cpp core/test_omnimanager.cpp gui/adding_form.cpp gui/admining.cpp gui/admining_details.cpp gui/auto_testing.cpp gui/auto_testing_details.cpp gui/change_password.cpp gui/choice_tests.cpp gui/edit_pass.cpp gui/edit_test_case.cpp gui/edit_tests_run_and_list.cpp gui/hand_testing_details.cpp gui/handtestingform.cpp gui/login.cpp gui/registration.cpp gui/report.cpp gui/send_form.cpp gui/test_cases.cpp main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents gui/adding_form.ui gui/admining.ui gui/admining_details.ui gui/auto_testing.ui gui/auto_testing_details.ui gui/change_password.ui gui/choice_tests.ui gui/edit_pass.ui gui/edit_test_case.ui gui/edit_tests_run_and_list.ui gui/hand_testing_details.ui gui/handtestingform.ui gui/login.ui gui/registration.ui gui/report.ui gui/send_form.ui gui/test_cases.ui mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	x86_64-linux-gnu-g++ -pipe -g -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_adding_form.cpp moc_admining.cpp moc_admining_details.cpp moc_auto_testing.cpp moc_auto_testing_details.cpp moc_change_password.cpp moc_choice_tests.cpp moc_edit_pass.cpp moc_edit_test_case.cpp moc_edit_tests_run_and_list.cpp moc_hand_testing_details.cpp moc_handtestingform.cpp moc_login.cpp moc_registration.cpp moc_report.cpp moc_send_form.cpp moc_test_cases.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_adding_form.cpp moc_admining.cpp moc_admining_details.cpp moc_auto_testing.cpp moc_auto_testing_details.cpp moc_change_password.cpp moc_choice_tests.cpp moc_edit_pass.cpp moc_edit_test_case.cpp moc_edit_tests_run_and_list.cpp moc_hand_testing_details.cpp moc_handtestingform.cpp moc_login.cpp moc_registration.cpp moc_report.cpp moc_send_form.cpp moc_test_cases.cpp moc_mainwindow.cpp
moc_adding_form.cpp: gui/adding_form.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/adding_form.h -o moc_adding_form.cpp

moc_admining.cpp: gui/admining.h \
		gui/admining_details.h \
		gui/edit_pass.h \
		core/Admin.hpp \
		core/Config.hpp \
		core/Base.hpp \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/admining.h -o moc_admining.cpp

moc_admining_details.cpp: gui/admining_details.h \
		gui/edit_pass.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/admining_details.h -o moc_admining_details.cpp

moc_auto_testing.cpp: gui/auto_testing.h \
		gui/auto_testing_details.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/auto_testing.h -o moc_auto_testing.cpp

moc_auto_testing_details.cpp: gui/auto_testing_details.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/auto_testing_details.h -o moc_auto_testing_details.cpp

moc_change_password.cpp: gui/change_password.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/change_password.h -o moc_change_password.cpp

moc_choice_tests.cpp: gui/choice_tests.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/choice_tests.h -o moc_choice_tests.cpp

moc_edit_pass.cpp: gui/edit_pass.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/edit_pass.h -o moc_edit_pass.cpp

moc_edit_test_case.cpp: gui/edit_test_case.h \
		core/file_manager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/edit_test_case.h -o moc_edit_test_case.cpp

moc_edit_tests_run_and_list.cpp: gui/edit_tests_run_and_list.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/edit_tests_run_and_list.h -o moc_edit_tests_run_and_list.cpp

moc_hand_testing_details.cpp: gui/hand_testing_details.h \
		gui/edit_test_case.h \
		core/file_manager.h \
		gui/edit_tests_run_and_list.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/hand_testing_details.h -o moc_hand_testing_details.cpp

moc_handtestingform.cpp: gui/handtestingform.h \
		gui/hand_testing_details.h \
		gui/edit_test_case.h \
		core/file_manager.h \
		gui/edit_tests_run_and_list.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/handtestingform.h -o moc_handtestingform.cpp

moc_login.cpp: gui/login.h \
		gui/registration.h \
		gui/change_password.h \
		core/Secure.hpp \
		core/Config.hpp \
		core/Base.hpp \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/login.h -o moc_login.cpp

moc_registration.cpp: gui/registration.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/registration.h -o moc_registration.cpp

moc_report.cpp: gui/report.h \
		gui/send_form.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/report.h -o moc_report.cpp

moc_send_form.cpp: gui/send_form.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/send_form.h -o moc_send_form.cpp

moc_test_cases.cpp: gui/test_cases.h \
		gui/choice_tests.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include gui/test_cases.h -o moc_test_cases.cpp

moc_mainwindow.cpp: mainwindow.h \
		gui/admining.h \
		gui/admining_details.h \
		gui/edit_pass.h \
		core/Admin.hpp \
		core/Config.hpp \
		core/Base.hpp \
		gui/auto_testing.h \
		gui/auto_testing_details.h \
		gui/handtestingform.h \
		gui/hand_testing_details.h \
		gui/edit_test_case.h \
		core/file_manager.h \
		gui/edit_tests_run_and_list.h \
		gui/test_cases.h \
		gui/choice_tests.h \
		gui/login.h \
		gui/registration.h \
		gui/change_password.h \
		core/Secure.hpp \
		gui/report.h \
		gui/send_form.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/dan/test/CDC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/dan/test/CDC -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_adding_form.h ui_admining.h ui_admining_details.h ui_auto_testing.h ui_auto_testing_details.h ui_change_password.h ui_choice_tests.h ui_edit_pass.h ui_edit_test_case.h ui_edit_tests_run_and_list.h ui_hand_testing_details.h ui_handtestingform.h ui_login.h ui_registration.h ui_report.h ui_send_form.h ui_test_cases.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_adding_form.h ui_admining.h ui_admining_details.h ui_auto_testing.h ui_auto_testing_details.h ui_change_password.h ui_choice_tests.h ui_edit_pass.h ui_edit_test_case.h ui_edit_tests_run_and_list.h ui_hand_testing_details.h ui_handtestingform.h ui_login.h ui_registration.h ui_report.h ui_send_form.h ui_test_cases.h ui_mainwindow.h
ui_adding_form.h: gui/adding_form.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/adding_form.ui -o ui_adding_form.h

ui_admining.h: gui/admining.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/admining.ui -o ui_admining.h

ui_admining_details.h: gui/admining_details.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/admining_details.ui -o ui_admining_details.h

ui_auto_testing.h: gui/auto_testing.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/auto_testing.ui -o ui_auto_testing.h

ui_auto_testing_details.h: gui/auto_testing_details.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/auto_testing_details.ui -o ui_auto_testing_details.h

ui_change_password.h: gui/change_password.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/change_password.ui -o ui_change_password.h

ui_choice_tests.h: gui/choice_tests.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/choice_tests.ui -o ui_choice_tests.h

ui_edit_pass.h: gui/edit_pass.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/edit_pass.ui -o ui_edit_pass.h

ui_edit_test_case.h: gui/edit_test_case.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/edit_test_case.ui -o ui_edit_test_case.h

ui_edit_tests_run_and_list.h: gui/edit_tests_run_and_list.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/edit_tests_run_and_list.ui -o ui_edit_tests_run_and_list.h

ui_hand_testing_details.h: gui/hand_testing_details.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/hand_testing_details.ui -o ui_hand_testing_details.h

ui_handtestingform.h: gui/handtestingform.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/handtestingform.ui -o ui_handtestingform.h

ui_login.h: gui/login.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/login.ui -o ui_login.h

ui_registration.h: gui/registration.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/registration.ui -o ui_registration.h

ui_report.h: gui/report.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/report.ui -o ui_report.h

ui_send_form.h: gui/send_form.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/send_form.ui -o ui_send_form.h

ui_test_cases.h: gui/test_cases.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic gui/test_cases.ui -o ui_test_cases.h

ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

Secure.o: core/Secure.cpp core/Secure.hpp \
		core/Config.hpp \
		core/Base.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Secure.o core/Secure.cpp

Admin.o: core/Admin.cpp core/Admin.hpp \
		core/Config.hpp \
		core/Base.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Admin.o core/Admin.cpp

Config.o: core/Config.cpp core/Config.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Config.o core/Config.cpp

Service.o: core/Service.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Service.o core/Service.cpp

admin_manager.o: core/admin_manager.cpp core/admin_manager.h \
		core/secure_manager.h \
		core/task_manager.h \
		core/test_omnimanager.h \
		core/test_manager.h \
		src/Config.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o admin_manager.o core/admin_manager.cpp

file_manager.o: core/file_manager.cpp core/file_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file_manager.o core/file_manager.cpp

secure_manager.o: core/secure_manager.cpp core/secure_manager.h \
		core/task_manager.h \
		core/test_omnimanager.h \
		core/test_manager.h \
		src/Config.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o secure_manager.o core/secure_manager.cpp

task_manager.o: core/task_manager.cpp core/task_manager.h \
		core/test_omnimanager.h \
		core/test_manager.h \
		src/Config.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o task_manager.o core/task_manager.cpp

test_case.o: core/test_case.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test_case.o core/test_case.cpp

test_manager.o: core/test_manager.cpp core/test_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test_manager.o core/test_manager.cpp

test_omnimanager.o: core/test_omnimanager.cpp core/test_omnimanager.h \
		core/test_manager.h \
		core/Options.h \
		core/Secure.hpp \
		core/Config.hpp \
		core/Base.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test_omnimanager.o core/test_omnimanager.cpp

adding_form.o: gui/adding_form.cpp gui/adding_form.h \
		ui_adding_form.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adding_form.o gui/adding_form.cpp

admining.o: gui/admining.cpp gui/admining.h \
		gui/admining_details.h \
		gui/edit_pass.h \
		core/Admin.hpp \
		core/Config.hpp \
		core/Base.hpp \
		ui_admining.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o admining.o gui/admining.cpp

admining_details.o: gui/admining_details.cpp gui/admining_details.h \
		gui/edit_pass.h \
		ui_admining_details.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o admining_details.o gui/admining_details.cpp

auto_testing.o: gui/auto_testing.cpp gui/auto_testing.h \
		gui/auto_testing_details.h \
		ui_auto_testing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o auto_testing.o gui/auto_testing.cpp

auto_testing_details.o: gui/auto_testing_details.cpp gui/auto_testing_details.h \
		ui_auto_testing_details.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o auto_testing_details.o gui/auto_testing_details.cpp

change_password.o: gui/change_password.cpp gui/change_password.h \
		ui_change_password.h \
		core/Secure.hpp \
		core/Config.hpp \
		core/Base.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o change_password.o gui/change_password.cpp

choice_tests.o: gui/choice_tests.cpp gui/choice_tests.h \
		ui_choice_tests.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o choice_tests.o gui/choice_tests.cpp

edit_pass.o: gui/edit_pass.cpp gui/edit_pass.h \
		ui_edit_pass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edit_pass.o gui/edit_pass.cpp

edit_test_case.o: gui/edit_test_case.cpp gui/edit_test_case.h \
		core/file_manager.h \
		ui_edit_test_case.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edit_test_case.o gui/edit_test_case.cpp

edit_tests_run_and_list.o: gui/edit_tests_run_and_list.cpp gui/edit_tests_run_and_list.h \
		ui_edit_tests_run_and_list.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edit_tests_run_and_list.o gui/edit_tests_run_and_list.cpp

hand_testing_details.o: gui/hand_testing_details.cpp gui/hand_testing_details.h \
		gui/edit_test_case.h \
		core/file_manager.h \
		gui/edit_tests_run_and_list.h \
		ui_hand_testing_details.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hand_testing_details.o gui/hand_testing_details.cpp

handtestingform.o: gui/handtestingform.cpp gui/handtestingform.h \
		gui/hand_testing_details.h \
		gui/edit_test_case.h \
		core/file_manager.h \
		gui/edit_tests_run_and_list.h \
		ui_handtestingform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o handtestingform.o gui/handtestingform.cpp

login.o: gui/login.cpp gui/login.h \
		gui/registration.h \
		gui/change_password.h \
		core/Secure.hpp \
		core/Config.hpp \
		core/Base.hpp \
		ui_login.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o gui/login.cpp

registration.o: gui/registration.cpp gui/registration.h \
		ui_registration.h \
		core/Secure.hpp \
		core/Config.hpp \
		core/Base.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registration.o gui/registration.cpp

report.o: gui/report.cpp gui/report.h \
		gui/send_form.h \
		ui_report.h \
		core/file_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o report.o gui/report.cpp

send_form.o: gui/send_form.cpp gui/send_form.h \
		ui_send_form.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o send_form.o gui/send_form.cpp

test_cases.o: gui/test_cases.cpp gui/test_cases.h \
		gui/choice_tests.h \
		ui_test_cases.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test_cases.o gui/test_cases.cpp

main.o: main.cpp mainwindow.h \
		gui/admining.h \
		gui/admining_details.h \
		gui/edit_pass.h \
		core/Admin.hpp \
		core/Config.hpp \
		core/Base.hpp \
		gui/auto_testing.h \
		gui/auto_testing_details.h \
		gui/handtestingform.h \
		gui/hand_testing_details.h \
		gui/edit_test_case.h \
		core/file_manager.h \
		gui/edit_tests_run_and_list.h \
		gui/test_cases.h \
		gui/choice_tests.h \
		gui/login.h \
		gui/registration.h \
		gui/change_password.h \
		core/Secure.hpp \
		gui/report.h \
		gui/send_form.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		gui/admining.h \
		gui/admining_details.h \
		gui/edit_pass.h \
		core/Admin.hpp \
		core/Config.hpp \
		core/Base.hpp \
		gui/auto_testing.h \
		gui/auto_testing_details.h \
		gui/handtestingform.h \
		gui/hand_testing_details.h \
		gui/edit_test_case.h \
		core/file_manager.h \
		gui/edit_tests_run_and_list.h \
		gui/test_cases.h \
		gui/choice_tests.h \
		gui/login.h \
		gui/registration.h \
		gui/change_password.h \
		core/Secure.hpp \
		gui/report.h \
		gui/send_form.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_adding_form.o: moc_adding_form.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adding_form.o moc_adding_form.cpp

moc_admining.o: moc_admining.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_admining.o moc_admining.cpp

moc_admining_details.o: moc_admining_details.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_admining_details.o moc_admining_details.cpp

moc_auto_testing.o: moc_auto_testing.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_auto_testing.o moc_auto_testing.cpp

moc_auto_testing_details.o: moc_auto_testing_details.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_auto_testing_details.o moc_auto_testing_details.cpp

moc_change_password.o: moc_change_password.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_change_password.o moc_change_password.cpp

moc_choice_tests.o: moc_choice_tests.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_choice_tests.o moc_choice_tests.cpp

moc_edit_pass.o: moc_edit_pass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_edit_pass.o moc_edit_pass.cpp

moc_edit_test_case.o: moc_edit_test_case.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_edit_test_case.o moc_edit_test_case.cpp

moc_edit_tests_run_and_list.o: moc_edit_tests_run_and_list.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_edit_tests_run_and_list.o moc_edit_tests_run_and_list.cpp

moc_hand_testing_details.o: moc_hand_testing_details.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hand_testing_details.o moc_hand_testing_details.cpp

moc_handtestingform.o: moc_handtestingform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_handtestingform.o moc_handtestingform.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_registration.o: moc_registration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registration.o moc_registration.cpp

moc_report.o: moc_report.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_report.o moc_report.cpp

moc_send_form.o: moc_send_form.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_send_form.o moc_send_form.cpp

moc_test_cases.o: moc_test_cases.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_test_cases.o moc_test_cases.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/testingSystem/bin || mkdir -p $(INSTALL_ROOT)/opt/testingSystem/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/testingSystem/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/testingSystem/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/testingSystem/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

