#!/bin/bash

# Удалить все

CDC_ROOT=/var/lib/CDC
CDC_USER=cdc

CDC_LOGIN=$CDC_ROOT/Login.cfg
CDC_ENTERED=$CDC_ROOT/Entered.cfg
CDC_EMERGENCY=$CDC_ROOT/Emergency

CDC_PROJECTS=$CDC_ROOT/Projects
CDC_LISTS=$CDC_ROOT/Lists
CDC_TESTS=$CDC_ROOT/Tests
CDC_TESTS_BIN=$CDC_ROOT/Tests_bin


# remove user
echo "[Remove] Remove user $CDC_USER"
userdel $CDC_USER

# remove dirs
echo "[Remove] Remove file structure"
rm -rf $CDC_ROOT
